export const USER_ROLES = {
  LAWYER: 'LAWYER',
  JUNIOR: 'JUNIOR',
  CLIENT: 'CLIENT',
  ADMIN: 'ADMIN',
  RESEARCHER: 'RESEARCHER'
};

export const USER_STATUS = {
  PENDING_PHONE_VERIFICATION: 'PENDING_PHONE_VERIFICATION',
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
};

export const CASE_STATUS = {
  OPEN: 'OPEN',
  CLOSED: 'CLOSED',
  PENDING: 'PENDING'
};

export const PAYMENT_STATUS = {
  PAID_IN_FULL: 'PAID_IN_FULL',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  NOT_INVOICED: 'NOT_INVOICED',
  OVERDUE: 'OVERDUE'
};

export const HEARING_STATUS = {
  PLANNED: 'PLANNED',
  COMPLETED: 'COMPLETED',
  POSTPONED: 'POSTPONED',
  CANCELLED: 'CANCELLED'
};